---

- name: install keystone
  hosts: "{{ host_group | default('openstack-cont') }}"
  roles:
    - ansible-keystone
  vars:
    openstack_keystone_database_url: "mysql://keystone:{{ MYSQL_KEYSTONE_PASS }}@{{ DATABASE_HOSTNAME }}/keystone"
    openstack_keystone_admin_token: "{{ ADMIN_TOKEN }}"
    openstack_keystone_tenants:
      - { name: admin, description: "Admin tenant" }
      - { name: service, description: "Service tenant" }
      - { name: demo, description: "Demo tenant" }
    openstack_keystone_users:
      - { name: admin, password: "{{ ADMIN_PASS }}", tenant: admin }
      - { name: demo, password: "{{ DEMO_PASS }}", tenant: demo }
      - { name: glance, password: "{{ GLANCE_PASS }}", tenant: service }
      - { name: nova, password: "{{ NOVA_PASS }}", tenant: service }
      - { name: neutron, password: "{{ NEUTRON_PASS }}", tenant: service }
    openstack_keystone_roles:
      - { name: admin, user: admin, tenant: admin }
      - { name: _member_, user: demo, tenant: demo }
      - { name: admin, user: glance, tenant: service }
      - { name: admin, user: nova, tenant: service }
      - { name: admin, user: neutron, tenant: service }
    openstack_keystone_services:
      - { name: keystone, service_type: identity }
      - { name: glance, service_type: image }
      - { name: nova, service_type: compute }
      - { name: neutron, service_type: network }
    openstack_keystone_endpoints:
      - service_name: keystone
        public_url: "http://{{ ansible_hostname }}:5000/v2.0"
        internal_url: "http://{{ ansible_hostname }}:5000/v2.0"
        admin_url: "http://{{ ansible_hostname }}:35357/v2.0"
      - service_name: glance
        public_url: "http://{{ ansible_hostname }}:9292/"
        internal_url: "http://{{ ansible_hostname }}:9292/"
        admin_url: "http://{{ ansible_hostname }}:9292/"
      - service_name: nova
        public_url: "http://{{ ansible_hostname }}:8774/v2.1"
        internal_url: "http://{{ ansible_hostname }}:8774/v2.1"
        admin_url: "http://{{ ansible_hostname }}:8774/v2.1"
      - service_name: neutron
        public_url: "http://{{ ansible_hostname }}:9696"
        internal_url: "http://{{ ansible_hostname }}:9696"
        admin_url: "http://{{ ansible_hostname }}:9696"
