---
- name: install memcached
  yum: name="{{ item }}" state=present
  with_items:
    - memcached
    - python-memcached

- name: set memcached
  template:
    src: memcached/memcached.j2
    dest: /etc/sysconfig/memcached
  notify: restart memcached
